### ISSUE TITLE
New format for validity files

### ISSUE THREAD

**Issue by gipert** [legend-exp/legend-data-format-specs#10]
The current JSONL format produces unreadable files. I propose to switch to YAML (which, unlike JSON, fully supports lists of records):
```yaml
- valid_from: 20230311T235840Z
  category: all
  reset: true
  apply:
  - l200-p03-r%-T%-all-config.json
  - l200-p03-r%-T%-cal-config.json
  - l200-p03-r000-T%-all-config.json

- valid_from: 20230317T211819Z
  category: all
  apply:
  - l200-p03-r001-T%-phy-config.json

- valid_from: 20240304T134049Z
  category: all
  reset: true
  apply:
  - l200-p42-r%-T%-all-config.json
  ```

I hope it's self-explanatory.
